#!/usr/bin/env bash

get_dns_info() {
  local domain="$1"
  local subdomain="$2"
  
  if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi
  
  for sub in "${subdomains[@]}"; do
    dns_output=$(dig "$sub.$domain" +short)
    dns_type=$(dig "$sub.$domain" +short -t ANY)
    
    if [ -n "$dns_output" ]; then
      echo "The subdomain $sub is a $dns_type record and points to $dns_output"
    else
      echo "The subdomain $sub does not exist or has no DNS record."
    fi
  done
}

if [ "$#" -eq 0 ]; then
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi

domain="$1"
subdomain="$2"

get_dns_info "$domain" "$subdomain"
